//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Inputs/Player Bindings.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerBindings : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerBindings()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Player Bindings"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""3f8f744d-db9d-4bc7-bac6-4e605b1b7c3b"",
            ""actions"": [
                {
                    ""name"": ""Mouse Movement"",
                    ""type"": ""Value"",
                    ""id"": ""76ada048-466a-4b2a-92d6-7ea3fdc42872"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Shoulder Torch"",
                    ""type"": ""Button"",
                    ""id"": ""9970ce7a-fb95-4708-8646-4a6e114e24f7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Body Movement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""0e732084-a13c-46f1-9e62-e23c4d5d05ef"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Item Interaction"",
                    ""type"": ""Button"",
                    ""id"": ""a7a7f6e6-feab-44b7-8032-d0696b425c41"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""General Interaction"",
                    ""type"": ""Button"",
                    ""id"": ""558dc761-1748-4b74-962b-449efc34d691"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Running"",
                    ""type"": ""Button"",
                    ""id"": ""3126570c-03f4-4416-8af0-d62ad76f0522"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Crouching"",
                    ""type"": ""Button"",
                    ""id"": ""35d03a04-65e5-40f4-829b-4de388c7b1ce"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""815abe89-4bc0-4aff-826d-d82163401698"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouse Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f880e8e5-adce-4784-b9ea-2adab947edbd"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouse Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""0762d747-8135-4ff0-a54f-8cd846fe6ba1"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Body Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d2540aeb-c3ed-43ca-aa72-5c617cfe8972"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Body Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""875590b9-0b94-42f4-89d2-7f21cd980bf3"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Body Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""8093449d-8235-4906-b025-e877d40d2628"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Body Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""5a5bf162-7b0f-4c7a-a5f7-73ebff9411b5"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Body Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""7312527e-befa-4ca8-8606-730c679f93b4"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Body Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3f8b695c-7f60-44e9-8286-9f4e2a02ad54"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Item Interaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0945125f-5dad-44cb-84ed-dca00f2bfe77"",
                    ""path"": ""<XInputController>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Item Interaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86ed334c-d37a-440f-bf48-8dee569e7065"",
                    ""path"": ""<DualShockGamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Item Interaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cb220f81-f1cc-4f56-8e5c-789cee892739"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""General Interaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8c8f8f6e-2ba5-4776-a48d-11799f8592a8"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""General Interaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9d4cc59f-8c30-4401-bec6-f98a60d7c26b"",
                    ""path"": ""<DualShockGamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""General Interaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6002f47d-0e79-4a80-baf3-a9a7b3a8ce3e"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Running"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""75536bab-ebda-4ad5-93d8-82f48d55bfd6"",
                    ""path"": ""<XInputController>/leftShoulder"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Running"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8dc33820-7949-465a-8ccd-477493bd810b"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Running"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e99cfca1-ed30-43b9-81ef-5107a7c51874"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouching"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c13833c5-679a-4f65-80a4-b2127e7421bc"",
                    ""path"": ""<XInputController>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouching"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4a0d95a0-f196-4d0e-b0fd-a86f7d62879e"",
                    ""path"": ""<DualShockGamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouching"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e1d0ea74-379d-44b3-9a3d-178b5a4eab24"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoulder Torch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0fe05fdf-4e15-414c-8306-b855cc73ae21"",
                    ""path"": ""<DualShockGamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoulder Torch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""446d549f-0616-49c1-a103-845a252003f8"",
                    ""path"": ""<XInputController>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoulder Torch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Car"",
            ""id"": ""02c9a010-c9a3-40b0-bfa0-6acd8b14eed7"",
            ""actions"": [
                {
                    ""name"": ""Car Movement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""ed13df06-ce48-4c8d-bdb6-296316d0a8e6"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Brakes"",
                    ""type"": ""Button"",
                    ""id"": ""536c01f6-1983-4318-832d-123cdd12cee6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Headlights"",
                    ""type"": ""Button"",
                    ""id"": ""7193b731-ab86-44e3-87d3-a6aa9bf144ab"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""e58fe7a1-e435-41d5-990d-6bb6a70e6613"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Car Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""ff539690-eeb1-4bc9-bfbf-dcd8c7c15d19"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Car Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""70fc7158-ae49-4d60-aad0-b09875c787b2"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Car Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""563558e1-d8fe-4b59-9a4b-a310481622bc"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Car Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""be7ce5cc-0a1f-4dba-accc-8e5ee5842a70"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Car Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""489ad058-cf78-4dc9-8e74-690c9c0c2d0d"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Car Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7af37518-f319-43e8-b27d-4c2160770fcc"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Brakes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1bcf135d-42c9-4fb0-ba59-320b615106dd"",
                    ""path"": ""<XInputController>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Brakes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""62386cac-521a-482d-8e76-f35ef4ac8eec"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Brakes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""26e2c9f3-697a-4400-bd59-a98ca0551ab4"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Headlights"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4ac5d95e-6241-4126-a399-9f29c8c2113e"",
                    ""path"": ""<XInputController>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Headlights"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4dd40ca1-eca1-4e0d-a6fb-9f2c6c17efb7"",
                    ""path"": ""<DualShockGamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Headlights"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""aabd815f-c80e-4558-a226-75e55671c54d"",
            ""actions"": [
                {
                    ""name"": ""Pull Up Pause Menu"",
                    ""type"": ""Button"",
                    ""id"": ""5ec55720-0598-4476-b847-7c58c7f5f106"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Navigation"",
                    ""type"": ""PassThrough"",
                    ""id"": ""2604ea22-89c3-4085-bfe6-cfffb729e9ff"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Submit"",
                    ""type"": ""Button"",
                    ""id"": ""8dfa8c35-da21-4552-aa03-97447baefab4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Open Journal"",
                    ""type"": ""Button"",
                    ""id"": ""c9fe520c-1a1e-4f87-a049-ffe990df370e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b9fd61b7-7204-415a-951c-ce18add2e1e0"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pull Up Pause Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2657f1f7-e354-41d8-8d24-fbfd7ad0d3ae"",
                    ""path"": ""<DualShockGamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pull Up Pause Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""89a44a9e-b566-4b2e-bf5f-817b62011e37"",
                    ""path"": ""<XInputController>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pull Up Pause Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Play Station"",
                    ""id"": ""96510d9a-88ef-410e-b8de-e7bc84c26464"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigation"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""477ac0de-9316-4141-8a44-7405ed5d005b"",
                    ""path"": ""<DualShockGamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""32560265-807c-471b-9397-7141edb715be"",
                    ""path"": ""<DualShockGamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""1a0ee4f0-45f0-457f-b570-98ac72dc5bbf"",
                    ""path"": ""<DualShockGamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""0c1fcef0-572d-4091-8a31-10403c8929e5"",
                    ""path"": ""<DualShockGamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Xbox"",
                    ""id"": ""937f7b62-1473-44e0-bb59-cfdd80e563f8"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigation"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""84ff7bff-9d6b-4cf0-a595-c45efd34216e"",
                    ""path"": ""<XInputController>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""2b64769b-746d-4ab4-9898-5e0b58478ce1"",
                    ""path"": ""<XInputController>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""175eb1c6-529e-444c-aedf-64ff600a4842"",
                    ""path"": ""<XInputController>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""0688a05e-908c-4e2b-a038-7dd25fdf9ea2"",
                    ""path"": ""<XInputController>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""e5354414-412c-44de-af90-18c7b1e24a6a"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigation"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""50596547-60f8-496c-9487-05415c249ddc"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""e5f33452-105b-4aa3-b9ac-7ecafce39205"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b632242a-8c29-45ca-9c62-c5c95588e557"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""610d3033-5abd-4992-950c-60390dc87a9f"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""fd31de91-a72c-4987-a8b1-71df55b20719"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f7857894-7118-4a56-b0e6-8250b63c4d1c"",
                    ""path"": ""<DualShockGamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""55104451-f040-4b37-ab4d-0535b8d1a59f"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d5dafc3f-2d43-4565-b85e-bedb565d2dd3"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Open Journal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1ce4605-1cf4-472a-8ff6-ffdbef3d2e7d"",
                    ""path"": ""<DualShockGamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Open Journal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3647fb4e-fc50-404b-9654-62861f1d79fe"",
                    ""path"": ""<XInputController>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Open Journal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Free Roam Camera"",
            ""id"": ""4e765b87-24ea-4779-897d-32a0fb80684f"",
            ""actions"": [
                {
                    ""name"": ""Mouse Movement"",
                    ""type"": ""Value"",
                    ""id"": ""0ac06e78-f404-408e-b20e-fe1c5cc2d58a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Spacial Movement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""95bd4e62-20f1-4604-a058-0cb36ad4cc13"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Lift Up"",
                    ""type"": ""Button"",
                    ""id"": ""40accbb6-812d-4a9d-900d-39933a969a0a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Push Down"",
                    ""type"": ""Button"",
                    ""id"": ""bdbdd706-2da0-42e4-ad71-c5403b45ab7a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""357537ee-0bb5-406a-9933-ca2ba993cd9a"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouse Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c5e8453c-020b-465e-a088-589603eba5a0"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouse Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eee11edb-ce0e-4728-89b4-6de7cfeb2355"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Lift Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""123af1c4-1b70-4598-8dc4-4241c7e32377"",
                    ""path"": ""<XInputController>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Lift Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5504a7c5-bb5f-4a5b-a537-13491a86fa14"",
                    ""path"": ""<DualShockGamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Lift Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""805178d0-b62c-467a-b268-3a70cc9522c6"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Push Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""44930bb6-0269-4995-bc60-16a2ac9b93bd"",
                    ""path"": ""<XInputController>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Push Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0177d85a-0df3-4e25-b277-635b09d9c2b4"",
                    ""path"": ""<DualShockGamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Push Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""b25b8327-0eaf-4bc5-8fbd-45feef1cb530"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spacial Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""516c6401-8386-424f-8eed-3a0a021183d8"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spacial Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ff97eeff-3539-472b-a66e-0891b8f6c303"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spacial Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""3e3d8293-cc0b-46a9-a919-d8705f3582b4"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spacial Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""05288bf0-25e9-437b-a34c-c07f3e5eeae6"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spacial Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""2feb1146-6ce6-4fa6-a630-10922364f28f"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spacial Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_MouseMovement = m_Player.FindAction("Mouse Movement", throwIfNotFound: true);
        m_Player_ShoulderTorch = m_Player.FindAction("Shoulder Torch", throwIfNotFound: true);
        m_Player_BodyMovement = m_Player.FindAction("Body Movement", throwIfNotFound: true);
        m_Player_ItemInteraction = m_Player.FindAction("Item Interaction", throwIfNotFound: true);
        m_Player_GeneralInteraction = m_Player.FindAction("General Interaction", throwIfNotFound: true);
        m_Player_Running = m_Player.FindAction("Running", throwIfNotFound: true);
        m_Player_Crouching = m_Player.FindAction("Crouching", throwIfNotFound: true);
        // Car
        m_Car = asset.FindActionMap("Car", throwIfNotFound: true);
        m_Car_CarMovement = m_Car.FindAction("Car Movement", throwIfNotFound: true);
        m_Car_Brakes = m_Car.FindAction("Brakes", throwIfNotFound: true);
        m_Car_Headlights = m_Car.FindAction("Headlights", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_PullUpPauseMenu = m_UI.FindAction("Pull Up Pause Menu", throwIfNotFound: true);
        m_UI_Navigation = m_UI.FindAction("Navigation", throwIfNotFound: true);
        m_UI_Submit = m_UI.FindAction("Submit", throwIfNotFound: true);
        m_UI_OpenJournal = m_UI.FindAction("Open Journal", throwIfNotFound: true);
        // Free Roam Camera
        m_FreeRoamCamera = asset.FindActionMap("Free Roam Camera", throwIfNotFound: true);
        m_FreeRoamCamera_MouseMovement = m_FreeRoamCamera.FindAction("Mouse Movement", throwIfNotFound: true);
        m_FreeRoamCamera_SpacialMovement = m_FreeRoamCamera.FindAction("Spacial Movement", throwIfNotFound: true);
        m_FreeRoamCamera_LiftUp = m_FreeRoamCamera.FindAction("Lift Up", throwIfNotFound: true);
        m_FreeRoamCamera_PushDown = m_FreeRoamCamera.FindAction("Push Down", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_MouseMovement;
    private readonly InputAction m_Player_ShoulderTorch;
    private readonly InputAction m_Player_BodyMovement;
    private readonly InputAction m_Player_ItemInteraction;
    private readonly InputAction m_Player_GeneralInteraction;
    private readonly InputAction m_Player_Running;
    private readonly InputAction m_Player_Crouching;
    public struct PlayerActions
    {
        private @PlayerBindings m_Wrapper;
        public PlayerActions(@PlayerBindings wrapper) { m_Wrapper = wrapper; }
        public InputAction @MouseMovement => m_Wrapper.m_Player_MouseMovement;
        public InputAction @ShoulderTorch => m_Wrapper.m_Player_ShoulderTorch;
        public InputAction @BodyMovement => m_Wrapper.m_Player_BodyMovement;
        public InputAction @ItemInteraction => m_Wrapper.m_Player_ItemInteraction;
        public InputAction @GeneralInteraction => m_Wrapper.m_Player_GeneralInteraction;
        public InputAction @Running => m_Wrapper.m_Player_Running;
        public InputAction @Crouching => m_Wrapper.m_Player_Crouching;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @MouseMovement.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMouseMovement;
                @MouseMovement.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMouseMovement;
                @MouseMovement.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMouseMovement;
                @ShoulderTorch.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoulderTorch;
                @ShoulderTorch.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoulderTorch;
                @ShoulderTorch.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoulderTorch;
                @BodyMovement.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBodyMovement;
                @BodyMovement.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBodyMovement;
                @BodyMovement.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBodyMovement;
                @ItemInteraction.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnItemInteraction;
                @ItemInteraction.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnItemInteraction;
                @ItemInteraction.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnItemInteraction;
                @GeneralInteraction.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGeneralInteraction;
                @GeneralInteraction.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGeneralInteraction;
                @GeneralInteraction.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGeneralInteraction;
                @Running.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRunning;
                @Running.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRunning;
                @Running.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRunning;
                @Crouching.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCrouching;
                @Crouching.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCrouching;
                @Crouching.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCrouching;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MouseMovement.started += instance.OnMouseMovement;
                @MouseMovement.performed += instance.OnMouseMovement;
                @MouseMovement.canceled += instance.OnMouseMovement;
                @ShoulderTorch.started += instance.OnShoulderTorch;
                @ShoulderTorch.performed += instance.OnShoulderTorch;
                @ShoulderTorch.canceled += instance.OnShoulderTorch;
                @BodyMovement.started += instance.OnBodyMovement;
                @BodyMovement.performed += instance.OnBodyMovement;
                @BodyMovement.canceled += instance.OnBodyMovement;
                @ItemInteraction.started += instance.OnItemInteraction;
                @ItemInteraction.performed += instance.OnItemInteraction;
                @ItemInteraction.canceled += instance.OnItemInteraction;
                @GeneralInteraction.started += instance.OnGeneralInteraction;
                @GeneralInteraction.performed += instance.OnGeneralInteraction;
                @GeneralInteraction.canceled += instance.OnGeneralInteraction;
                @Running.started += instance.OnRunning;
                @Running.performed += instance.OnRunning;
                @Running.canceled += instance.OnRunning;
                @Crouching.started += instance.OnCrouching;
                @Crouching.performed += instance.OnCrouching;
                @Crouching.canceled += instance.OnCrouching;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // Car
    private readonly InputActionMap m_Car;
    private ICarActions m_CarActionsCallbackInterface;
    private readonly InputAction m_Car_CarMovement;
    private readonly InputAction m_Car_Brakes;
    private readonly InputAction m_Car_Headlights;
    public struct CarActions
    {
        private @PlayerBindings m_Wrapper;
        public CarActions(@PlayerBindings wrapper) { m_Wrapper = wrapper; }
        public InputAction @CarMovement => m_Wrapper.m_Car_CarMovement;
        public InputAction @Brakes => m_Wrapper.m_Car_Brakes;
        public InputAction @Headlights => m_Wrapper.m_Car_Headlights;
        public InputActionMap Get() { return m_Wrapper.m_Car; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CarActions set) { return set.Get(); }
        public void SetCallbacks(ICarActions instance)
        {
            if (m_Wrapper.m_CarActionsCallbackInterface != null)
            {
                @CarMovement.started -= m_Wrapper.m_CarActionsCallbackInterface.OnCarMovement;
                @CarMovement.performed -= m_Wrapper.m_CarActionsCallbackInterface.OnCarMovement;
                @CarMovement.canceled -= m_Wrapper.m_CarActionsCallbackInterface.OnCarMovement;
                @Brakes.started -= m_Wrapper.m_CarActionsCallbackInterface.OnBrakes;
                @Brakes.performed -= m_Wrapper.m_CarActionsCallbackInterface.OnBrakes;
                @Brakes.canceled -= m_Wrapper.m_CarActionsCallbackInterface.OnBrakes;
                @Headlights.started -= m_Wrapper.m_CarActionsCallbackInterface.OnHeadlights;
                @Headlights.performed -= m_Wrapper.m_CarActionsCallbackInterface.OnHeadlights;
                @Headlights.canceled -= m_Wrapper.m_CarActionsCallbackInterface.OnHeadlights;
            }
            m_Wrapper.m_CarActionsCallbackInterface = instance;
            if (instance != null)
            {
                @CarMovement.started += instance.OnCarMovement;
                @CarMovement.performed += instance.OnCarMovement;
                @CarMovement.canceled += instance.OnCarMovement;
                @Brakes.started += instance.OnBrakes;
                @Brakes.performed += instance.OnBrakes;
                @Brakes.canceled += instance.OnBrakes;
                @Headlights.started += instance.OnHeadlights;
                @Headlights.performed += instance.OnHeadlights;
                @Headlights.canceled += instance.OnHeadlights;
            }
        }
    }
    public CarActions @Car => new CarActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private IUIActions m_UIActionsCallbackInterface;
    private readonly InputAction m_UI_PullUpPauseMenu;
    private readonly InputAction m_UI_Navigation;
    private readonly InputAction m_UI_Submit;
    private readonly InputAction m_UI_OpenJournal;
    public struct UIActions
    {
        private @PlayerBindings m_Wrapper;
        public UIActions(@PlayerBindings wrapper) { m_Wrapper = wrapper; }
        public InputAction @PullUpPauseMenu => m_Wrapper.m_UI_PullUpPauseMenu;
        public InputAction @Navigation => m_Wrapper.m_UI_Navigation;
        public InputAction @Submit => m_Wrapper.m_UI_Submit;
        public InputAction @OpenJournal => m_Wrapper.m_UI_OpenJournal;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void SetCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterface != null)
            {
                @PullUpPauseMenu.started -= m_Wrapper.m_UIActionsCallbackInterface.OnPullUpPauseMenu;
                @PullUpPauseMenu.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnPullUpPauseMenu;
                @PullUpPauseMenu.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnPullUpPauseMenu;
                @Navigation.started -= m_Wrapper.m_UIActionsCallbackInterface.OnNavigation;
                @Navigation.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnNavigation;
                @Navigation.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnNavigation;
                @Submit.started -= m_Wrapper.m_UIActionsCallbackInterface.OnSubmit;
                @Submit.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnSubmit;
                @Submit.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnSubmit;
                @OpenJournal.started -= m_Wrapper.m_UIActionsCallbackInterface.OnOpenJournal;
                @OpenJournal.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnOpenJournal;
                @OpenJournal.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnOpenJournal;
            }
            m_Wrapper.m_UIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @PullUpPauseMenu.started += instance.OnPullUpPauseMenu;
                @PullUpPauseMenu.performed += instance.OnPullUpPauseMenu;
                @PullUpPauseMenu.canceled += instance.OnPullUpPauseMenu;
                @Navigation.started += instance.OnNavigation;
                @Navigation.performed += instance.OnNavigation;
                @Navigation.canceled += instance.OnNavigation;
                @Submit.started += instance.OnSubmit;
                @Submit.performed += instance.OnSubmit;
                @Submit.canceled += instance.OnSubmit;
                @OpenJournal.started += instance.OnOpenJournal;
                @OpenJournal.performed += instance.OnOpenJournal;
                @OpenJournal.canceled += instance.OnOpenJournal;
            }
        }
    }
    public UIActions @UI => new UIActions(this);

    // Free Roam Camera
    private readonly InputActionMap m_FreeRoamCamera;
    private IFreeRoamCameraActions m_FreeRoamCameraActionsCallbackInterface;
    private readonly InputAction m_FreeRoamCamera_MouseMovement;
    private readonly InputAction m_FreeRoamCamera_SpacialMovement;
    private readonly InputAction m_FreeRoamCamera_LiftUp;
    private readonly InputAction m_FreeRoamCamera_PushDown;
    public struct FreeRoamCameraActions
    {
        private @PlayerBindings m_Wrapper;
        public FreeRoamCameraActions(@PlayerBindings wrapper) { m_Wrapper = wrapper; }
        public InputAction @MouseMovement => m_Wrapper.m_FreeRoamCamera_MouseMovement;
        public InputAction @SpacialMovement => m_Wrapper.m_FreeRoamCamera_SpacialMovement;
        public InputAction @LiftUp => m_Wrapper.m_FreeRoamCamera_LiftUp;
        public InputAction @PushDown => m_Wrapper.m_FreeRoamCamera_PushDown;
        public InputActionMap Get() { return m_Wrapper.m_FreeRoamCamera; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(FreeRoamCameraActions set) { return set.Get(); }
        public void SetCallbacks(IFreeRoamCameraActions instance)
        {
            if (m_Wrapper.m_FreeRoamCameraActionsCallbackInterface != null)
            {
                @MouseMovement.started -= m_Wrapper.m_FreeRoamCameraActionsCallbackInterface.OnMouseMovement;
                @MouseMovement.performed -= m_Wrapper.m_FreeRoamCameraActionsCallbackInterface.OnMouseMovement;
                @MouseMovement.canceled -= m_Wrapper.m_FreeRoamCameraActionsCallbackInterface.OnMouseMovement;
                @SpacialMovement.started -= m_Wrapper.m_FreeRoamCameraActionsCallbackInterface.OnSpacialMovement;
                @SpacialMovement.performed -= m_Wrapper.m_FreeRoamCameraActionsCallbackInterface.OnSpacialMovement;
                @SpacialMovement.canceled -= m_Wrapper.m_FreeRoamCameraActionsCallbackInterface.OnSpacialMovement;
                @LiftUp.started -= m_Wrapper.m_FreeRoamCameraActionsCallbackInterface.OnLiftUp;
                @LiftUp.performed -= m_Wrapper.m_FreeRoamCameraActionsCallbackInterface.OnLiftUp;
                @LiftUp.canceled -= m_Wrapper.m_FreeRoamCameraActionsCallbackInterface.OnLiftUp;
                @PushDown.started -= m_Wrapper.m_FreeRoamCameraActionsCallbackInterface.OnPushDown;
                @PushDown.performed -= m_Wrapper.m_FreeRoamCameraActionsCallbackInterface.OnPushDown;
                @PushDown.canceled -= m_Wrapper.m_FreeRoamCameraActionsCallbackInterface.OnPushDown;
            }
            m_Wrapper.m_FreeRoamCameraActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MouseMovement.started += instance.OnMouseMovement;
                @MouseMovement.performed += instance.OnMouseMovement;
                @MouseMovement.canceled += instance.OnMouseMovement;
                @SpacialMovement.started += instance.OnSpacialMovement;
                @SpacialMovement.performed += instance.OnSpacialMovement;
                @SpacialMovement.canceled += instance.OnSpacialMovement;
                @LiftUp.started += instance.OnLiftUp;
                @LiftUp.performed += instance.OnLiftUp;
                @LiftUp.canceled += instance.OnLiftUp;
                @PushDown.started += instance.OnPushDown;
                @PushDown.performed += instance.OnPushDown;
                @PushDown.canceled += instance.OnPushDown;
            }
        }
    }
    public FreeRoamCameraActions @FreeRoamCamera => new FreeRoamCameraActions(this);
    public interface IPlayerActions
    {
        void OnMouseMovement(InputAction.CallbackContext context);
        void OnShoulderTorch(InputAction.CallbackContext context);
        void OnBodyMovement(InputAction.CallbackContext context);
        void OnItemInteraction(InputAction.CallbackContext context);
        void OnGeneralInteraction(InputAction.CallbackContext context);
        void OnRunning(InputAction.CallbackContext context);
        void OnCrouching(InputAction.CallbackContext context);
    }
    public interface ICarActions
    {
        void OnCarMovement(InputAction.CallbackContext context);
        void OnBrakes(InputAction.CallbackContext context);
        void OnHeadlights(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnPullUpPauseMenu(InputAction.CallbackContext context);
        void OnNavigation(InputAction.CallbackContext context);
        void OnSubmit(InputAction.CallbackContext context);
        void OnOpenJournal(InputAction.CallbackContext context);
    }
    public interface IFreeRoamCameraActions
    {
        void OnMouseMovement(InputAction.CallbackContext context);
        void OnSpacialMovement(InputAction.CallbackContext context);
        void OnLiftUp(InputAction.CallbackContext context);
        void OnPushDown(InputAction.CallbackContext context);
    }
}
